export const tutorialSteps = [
  {
    id: 'welcome',
    title: 'Welcome to NaliChat',
    description: 'Your collaborative music production studio. Let\'s learn the essentials!',
    targetSelector: null,
    placement: 'center',
  },
  {
    id: 'explore',
    title: 'Explore Music',
    description: 'Browse trending tracks, discover artists, and interact with the community.',
    targetSelector: 'a[href="/explore"]',
    placement: 'bottom',
  },
  {
    id: 'messages',
    title: 'Real-time Messages',
    description: 'Chat with collaborators, send files, and record voice messages in conversations.',
    targetSelector: 'a[href="/messages"]',
    placement: 'bottom',
  },
  {
    id: 'studio',
    title: 'Multi-track Studio',
    description: 'Create projects, manage audio tracks, collaborate on mixing & mastering.',
    targetSelector: 'a[href="/studio"]',
    placement: 'bottom',
  },
  {
    id: 'record',
    title: 'Record Audio',
    description: 'Record vocals, instruments, or beats directly in the app with real-time feedback.',
    targetSelector: 'a[href="/record"]',
    placement: 'bottom',
  },
  {
    id: 'files',
    title: 'Shared Files',
    description: 'Upload, organize, and share audio files with team members or sell them.',
    targetSelector: 'a[href="/files"]',
    placement: 'bottom',
  },
  {
    id: 'playlists',
    title: 'Playlists',
    description: 'Create custom playlists and organize your favorite tracks.',
    targetSelector: 'a[href="/playlists"]',
    placement: 'bottom',
  },
  {
    id: 'network',
    title: 'Network',
    description: 'Connect with other artists and build your creative community.',
    targetSelector: 'a[href="/network"]',
    placement: 'bottom',
  },
  {
    id: 'nali',
    title: 'Meet Nali AI',
    description: 'Your AI assistant. Ask for help with production, tips, or restart this tutorial anytime!',
    targetSelector: null,
    placement: 'center',
  },
  {
    id: 'complete',
    title: 'You\'re All Set!',
    description: 'Start creating, exploring, and collaborating. Have fun!',
    targetSelector: null,
    placement: 'center',
  },
];