import { useEffect,useRef,useState } from "react";
import { ArrowLeft,Download,Film,Music2,Sparkles,Upload,Wand2 } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { secureUploadFile } from "@/lib/secureUpload";
import { base44 } from "@/api/base44Client";
const STYLES=["Cinematic 3D Animation","Graphic Novel","Neon Cyberpunk","Dreamlike Animation","Anime-inspired Original"];
export default function MusicVideoGenerator(){
 const nav=useNavigate(),canvas=useRef(null),audio=useRef(null),raf=useRef(0),images=useRef([]),motionVideos=useRef([]);
 const [file,setFile]=useState(null),[url,setUrl]=useState(""),[style,setStyle]=useState(STYLES[0]),[concept,setConcept]=useState(""),[busy,setBusy]=useState(false),[status,setStatus]=useState(""),[plan,setPlan]=useState(null),[video,setVideo]=useState(""),[duration,setDuration]=useState(0),[clipBusy,setClipBusy]=useState(null),[allMotionBusy,setAllMotionBusy]=useState(false);
 useEffect(()=>()=>{cancelAnimationFrame(raf.current);if(url)URL.revokeObjectURL(url);},[url]);
 const pick=e=>{const f=e.target.files?.[0];if(!f)return;setFile(f);setUrl(URL.createObjectURL(f));setPlan(null);setVideo("");};
 const preload=async scenes=>{images.current=await Promise.all(scenes.map(s=>new Promise(resolve=>{if(!s.image_url)return resolve(null);const i=new Image();i.crossOrigin="anonymous";i.onload=()=>resolve(i);i.onerror=()=>resolve(null);i.src=s.image_url;})));};
 const storyboard=async()=>{if(!file)return;setBusy(true);try{setStatus("Uploading song…");const up=await secureUploadFile({file});setStatus("Analyzing song and planning real video scenes…");const res=await base44.functions.invoke("generateMusicVideoStoryboard",{audio_url:up.file_url,title:file.name.replace(/\.[^.]+$/,""),concept,style,duration});const data=res?.data||res;if(data?.error)throw new Error(data.error);setPlan(data);await preload(data.scenes||[]);setStatus("Storyboard ready. Generate AI video clips for every scene before rendering.");}catch(e){setStatus(e?.response?.data?.error||e?.message||"Generation failed");}finally{setBusy(false);}};
 const generateMotionClip=async(s)=>{setClipBusy(s.id);setStatus(`Generating real AI video for ${s.title}…`);try{const res=await base44.functions.invoke("generateMusicVideoClip",{prompt:`${s.prompt}. Motion: ${s.motion}. Original cinematic animated music-video shot, no text or logos.`});const data=res?.data||res;if(data?.error)throw new Error(data.error);setPlan(p=>({...p,scenes:p.scenes.map(x=>x.id===s.id?{...x,video_url:data.video_url}:x)}));setStatus("Real AI video clip ready.");}catch(e){setStatus(e?.response?.data?.error||e?.message||"Real AI video generation failed. Retry this scene before rendering.");}finally{setClipBusy(null);}};
 const generateAllMotion=async()=>{if(!plan?.scenes?.length)return;setAllMotionBusy(true);let next=[...plan.scenes],done=0,failed=0,firstError="";try{for(let i=0;i<next.length;i++){if(next[i].video_url){done++;continue;}setClipBusy(next[i].id);setStatus(`Generating REAL AI video clip ${i+1} of ${next.length}…`);try{const res=await base44.functions.invoke("generateMusicVideoClip",{prompt:`${next[i].prompt}. Motion: ${next[i].motion}. Original cinematic animated music-video shot with continuous subject and camera movement, no text or logos.`});const data=res?.data||res;if(data?.video_url){next[i]={...next[i],video_url:data.video_url};done++;setPlan(p=>({...p,scenes:[...next]}));}else{failed++;firstError||=data?.error||"Video provider returned no clip";}}catch(e){failed++;firstError||=e?.response?.data?.error||e?.message||"AI video generation failed";console.warn("Video scene failed",next[i].id,e);}}setStatus(failed?`${done}/${next.length} real video clips generated. ${failed} failed. ${firstError}`:`All ${done} real AI video clips are ready. You can render the full music video.`);}finally{setClipBusy(null);setAllMotionBusy(false);}};
 const preloadMotion=async scenes=>{motionVideos.current=scenes.map(s=>{if(!s.video_url)return null;const v=document.createElement("video");v.crossOrigin="anonymous";v.muted=true;v.loop=true;v.playsInline=true;v.preload="auto";v.src=s.video_url;return v;});await Promise.all(motionVideos.current.filter(Boolean).map(v=>new Promise(r=>{if(v.readyState>=2)return r();v.onloadeddata=()=>r();v.onerror=()=>r();})));};
 const draw=()=>{const c=canvas.current,a=audio.current;if(!c||!a)return;const x=c.getContext("2d"),t=a.currentTime||0,scenes=plan?.scenes||[],seg=Math.max(1,(a.duration||duration||180)/Math.max(1,scenes.length)),idx=Math.min(scenes.length-1,Math.floor(t/seg)),local=(t%seg)/seg,img=images.current[idx],mv=motionVideos.current[idx];x.fillStyle="#050509";x.fillRect(0,0,c.width,c.height);if(mv&&mv.readyState>=2){const target=(local*(mv.duration||1))%(mv.duration||1);if(Math.abs((mv.currentTime||0)-target)>.2)try{mv.currentTime=target}catch{};const ratio=Math.max(c.width/mv.videoWidth,c.height/mv.videoHeight),w=mv.videoWidth*ratio,h=mv.videoHeight*ratio;x.drawImage(mv,(c.width-w)/2,(c.height-h)/2,w,h);}else if(img){const scale=1.06+local*.08,iw=img.width,ih=img.height,ratio=Math.max(c.width/iw,c.height/ih)*scale,w=iw*ratio,h=ih*ratio,pan=Math.sin(local*Math.PI*2)*30;x.save();x.globalAlpha=1;x.drawImage(img,(c.width-w)/2+pan,(c.height-h)/2,w,h);x.restore();}else{const g=x.createLinearGradient(0,0,c.width,c.height);g.addColorStop(0,"#7c3aed");g.addColorStop(1,"#ec4899");x.fillStyle=g;x.fillRect(0,0,c.width,c.height);}const fade=Math.min(1,local*5,(1-local)*5);x.fillStyle=`rgba(0,0,0,${.28*(1-fade)})`;x.fillRect(0,0,c.width,c.height);raf.current=requestAnimationFrame(draw);};
 useEffect(()=>{cancelAnimationFrame(raf.current);if(plan){preloadMotion(plan.scenes||[]).finally(draw);}return()=>cancelAnimationFrame(raf.current);},[plan]);
 const render=async()=>{if(!plan||!audio.current)return;const missing=(plan.scenes||[]).filter(s=>!s.video_url);if(missing.length){setStatus(`Cannot render yet: ${missing.length} scene${missing.length===1?" is":"s are"} still images. Generate REAL AI video for every scene first.`);return;}setBusy(true);setStatus("Rendering full-song 1080p video from real AI video clips…");const a=audio.current,c=canvas.current;a.pause();a.currentTime=0;const cs=c.captureStream(30);let as;try{as=a.captureStream?.()||a.mozCaptureStream?.();}catch{}const tracks=[...cs.getVideoTracks(),...(as?.getAudioTracks()||[])],stream=new MediaStream(tracks),mime=["video/webm;codecs=vp9,opus","video/webm;codecs=vp8,opus","video/webm"].find(MediaRecorder.isTypeSupported)||"",rec=new MediaRecorder(stream,mime?{mimeType:mime,videoBitsPerSecond:14000000}:undefined),chunks=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=()=>{setVideo(URL.createObjectURL(new Blob(chunks,{type:rec.mimeType||"video/webm"})));tracks.forEach(t=>t.stop());setBusy(false);setStatus("HD music video complete.");};a.onended=()=>rec.state!=="inactive"&&rec.stop();rec.start(1000);await a.play();};
 return <div className="min-h-screen bg-background pb-24"><div className="max-w-4xl mx-auto p-4 sm:p-6"><div className="flex gap-3 items-center mb-6"><Button variant="ghost" size="icon" onClick={()=>nav(-1)}><ArrowLeft/></Button><div><h1 className="text-3xl font-black flex gap-2 items-center"><Film className="text-primary"/>AI Music Video Generator</h1><p className="text-muted-foreground">A new NaliChat creative tool is on the way.</p></div></div><section className="rounded-3xl border bg-card p-8 sm:p-12 text-center space-y-5"><div className="mx-auto w-16 h-16 rounded-2xl bg-primary/10 flex items-center justify-center"><Film className="w-8 h-8 text-primary"/></div><div><div className="inline-flex rounded-full border px-3 py-1 text-xs font-bold uppercase tracking-wider text-primary mb-4">Coming Soon</div><h2 className="text-2xl sm:text-3xl font-black">AI Music Video Generator</h2></div><p className="text-muted-foreground max-w-2xl mx-auto">We’re building a better music video experience for NaliChat creators. Soon you’ll be able to turn your music and creative ideas into original AI-generated video scenes and complete music videos.</p><p className="text-sm text-muted-foreground">We’re holding the generator back until it meets our quality standards. Stay tuned.</p></section></div></div>;
}