import { useEffect,useRef,useState } from "react";
import { ArrowLeft, Film, Upload, Sparkles, Play, Download, WandSparkles, Loader2 } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { secureUploadFile } from "@/lib/secureUpload";
import { base44 } from "@/api/base44Client";

const STYLES=["Cinematic 3D Animation","Graphic Novel","Neon Cyberpunk","Dreamlike Animation","Anime-inspired Original"];

export default function MusicVideoGenerator(){
 const nav=useNavigate(),canvas=useRef(null),audio=useRef(null),raf=useRef(0),images=useRef([]),motionVideos=useRef([]);
 const [file,setFile]=useState(null),[url,setUrl]=useState(""),[style,setStyle]=useState(STYLES[0]),[concept,setConcept]=useState(""),[busy,setBusy]=useState(false),[status,setStatus]=useState(""),[plan,setPlan]=useState(null),[video,setVideo]=useState(""),[duration,setDuration]=useState(0),[clipBusy,setClipBusy]=useState(null),[allMotionBusy,setAllMotionBusy]=useState(false);
 useEffect(()=>()=>{cancelAnimationFrame(raf.current);if(url)URL.revokeObjectURL(url);},[url]);
 const pick=e=>{const f=e.target.files?.[0];if(!f)return;setFile(f);setUrl(URL.createObjectURL(f));setPlan(null);setVideo("");setStatus("Song loaded. Add a concept or let NaliBase direct it.");};
 const preload=async scenes=>{images.current=await Promise.all(scenes.map(s=>new Promise(resolve=>{if(!s.image_url)return resolve(null);const i=new Image();i.crossOrigin="anonymous";i.onload=()=>resolve(i);i.onerror=()=>resolve(null);i.src=s.image_url;})));};
 const storyboard=async()=>{if(!file)return;setBusy(true);try{setStatus("Uploading song…");const up=await secureUploadFile({file});setStatus("Analyzing song and directing scenes…");const res=await base44.functions.invoke("generateMusicVideoStoryboard",{audio_url:up.file_url,title:file.name.replace(/\.[^.]+$/,""),concept,style,duration});const data=res?.data||res;if(data?.error)throw new Error(data.error);setPlan(data);await preload(data.scenes||[]);setStatus("Storyboard ready. Review the scenes, then generate motion.");}catch(e){setStatus(e?.response?.data?.error||e?.message||"Storyboard generation failed");}finally{setBusy(false);}};
 const generateMotionClip=async s=>{setClipBusy(s.id);setStatus(`Generating AI video for ${s.title}…`);try{const res=await base44.functions.invoke("generateMusicVideoClip",{prompt:`${s.prompt}. Motion: ${s.motion}. Original cinematic music-video shot, continuous subject and camera movement, no text or logos.`});const data=res?.data||res;if(data?.error)throw new Error(data.error);setPlan(p=>({...p,scenes:p.scenes.map(x=>x.id===s.id?{...x,video_url:data.video_url}:x)}));setStatus("Scene clip ready.");}catch(e){setStatus(e?.response?.data?.error||e?.message||"AI video generation failed. You can retry this scene.");}finally{setClipBusy(null);}};
 const generateAllMotion=async()=>{if(!plan?.scenes?.length)return;setAllMotionBusy(true);let next=[...plan.scenes],done=0,failed=0,firstError="";try{for(let i=0;i<next.length;i++){if(next[i].video_url){done++;continue;}setClipBusy(next[i].id);setStatus(`Generating scene ${i+1} of ${next.length}…`);try{const res=await base44.functions.invoke("generateMusicVideoClip",{prompt:`${next[i].prompt}. Motion: ${next[i].motion}. Original cinematic music-video shot with continuous subject and camera movement, no text or logos.`});const data=res?.data||res;if(data?.video_url){next[i]={...next[i],video_url:data.video_url};done++;setPlan(p=>({...p,scenes:[...next]}));}else{failed++;firstError||=data?.error||"Video provider returned no clip";}}catch(e){failed++;firstError||=e?.response?.data?.error||e?.message||"AI video generation failed";}}setStatus(failed?`${done}/${next.length} clips generated. ${failed} need retry. ${firstError}`:`All ${done} clips are ready. Render the full video when you're ready.`);}finally{setClipBusy(null);setAllMotionBusy(false);}};
 const preloadMotion=async scenes=>{motionVideos.current=scenes.map(s=>{if(!s.video_url)return null;const v=document.createElement("video");v.crossOrigin="anonymous";v.muted=true;v.loop=true;v.playsInline=true;v.preload="auto";v.src=s.video_url;return v;});await Promise.all(motionVideos.current.filter(Boolean).map(v=>new Promise(r=>{if(v.readyState>=2)return r();v.onloadeddata=()=>r();v.onerror=()=>r();})));};
 const draw=()=>{const c=canvas.current,a=audio.current;if(!c||!a||!plan?.scenes?.length)return;const x=c.getContext("2d"),t=a.currentTime||0,scenes=plan.scenes,seg=Math.max(1,(a.duration||duration||180)/scenes.length),idx=Math.min(scenes.length-1,Math.floor(t/seg)),local=(t%seg)/seg,img=images.current[idx],mv=motionVideos.current[idx];x.fillStyle="#050509";x.fillRect(0,0,c.width,c.height);if(mv&&mv.readyState>=2&&mv.videoWidth){const target=(local*(mv.duration||1))%(mv.duration||1);if(Math.abs((mv.currentTime||0)-target)>.2)try{mv.currentTime=target}catch{}const ratio=Math.max(c.width/mv.videoWidth,c.height/mv.videoHeight),w=mv.videoWidth*ratio,h=mv.videoHeight*ratio;x.drawImage(mv,(c.width-w)/2,(c.height-h)/2,w,h);}else if(img){const scale=1.06+local*.08,ratio=Math.max(c.width/img.width,c.height/img.height)*scale,w=img.width*ratio,h=img.height*ratio,pan=Math.sin(local*Math.PI*2)*30;x.drawImage(img,(c.width-w)/2+pan,(c.height-h)/2,w,h);}else{const g=x.createLinearGradient(0,0,c.width,c.height);g.addColorStop(0,"#7c3aed");g.addColorStop(1,"#ec4899");x.fillStyle=g;x.fillRect(0,0,c.width,c.height);}raf.current=requestAnimationFrame(draw);};
 useEffect(()=>{cancelAnimationFrame(raf.current);if(plan)preloadMotion(plan.scenes||[]).finally(draw);return()=>cancelAnimationFrame(raf.current);},[plan]);
 const render=async()=>{if(!plan||!audio.current)return;const missing=(plan.scenes||[]).filter(s=>!s.video_url);if(missing.length){setStatus(`Generate motion for the remaining ${missing.length} scene${missing.length===1?"":"s"} before rendering.`);return;}if(!canvas.current.captureStream||typeof MediaRecorder==="undefined"){setStatus("This browser cannot render the final video. Try a current desktop Chrome or Edge browser.");return;}setBusy(true);setStatus("Rendering your full music video…");const a=audio.current,c=canvas.current;a.pause();a.currentTime=0;const cs=c.captureStream(30);let as;try{as=a.captureStream?.()||a.mozCaptureStream?.();}catch{}const tracks=[...cs.getVideoTracks(),...(as?.getAudioTracks()||[])],stream=new MediaStream(tracks),mime=["video/webm;codecs=vp9,opus","video/webm;codecs=vp8,opus","video/webm"].find(MediaRecorder.isTypeSupported)||"",rec=new MediaRecorder(stream,mime?{mimeType:mime,videoBitsPerSecond:14000000}:undefined),chunks=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=()=>{setVideo(URL.createObjectURL(new Blob(chunks,{type:rec.mimeType||"video/webm"})));tracks.forEach(t=>t.stop());setBusy(false);setStatus("Music video complete.");};a.onended=()=>rec.state!=="inactive"&&rec.stop();rec.start(1000);await a.play();};
 const ready=plan?.scenes?.filter(s=>s.video_url).length||0,total=plan?.scenes?.length||0;
 return <div className="min-h-screen bg-background pb-24"><div className="max-w-6xl mx-auto p-4 sm:p-6 space-y-6">
  <header className="flex gap-3 items-center"><Button variant="ghost" size="icon" onClick={()=>nav(-1)}><ArrowLeft/></Button><div className="flex-1"><div className="text-xs font-bold tracking-[.22em] text-primary">NALIBASE · VISUALIZE</div><h1 className="text-3xl sm:text-4xl font-black flex gap-2 items-center"><Film className="text-primary"/>Music Video Lab</h1><p className="text-muted-foreground">Turn a finished song into a directed storyboard, AI motion scenes, and a full music video.</p></div></header>
  <div className="grid lg:grid-cols-[.85fr_1.15fr] gap-6">
   <section className="rounded-3xl border bg-card p-5 sm:p-6 space-y-5">
    <div><h2 className="text-xl font-black">1. Load your song</h2><p className="text-sm text-muted-foreground">MP3, WAV, M4A, or other browser-supported audio.</p></div>
    <label className="block rounded-2xl border-2 border-dashed p-7 text-center cursor-pointer hover:bg-muted/30 transition"><Upload className="mx-auto mb-2 text-primary"/><div className="font-bold">{file?file.name:"Choose audio file"}</div><div className="text-xs text-muted-foreground mt-1">Your audio drives the final video timing.</div><input className="hidden" type="file" accept="audio/*" onChange={pick}/></label>
    {url&&<audio ref={audio} src={url} controls className="w-full" onLoadedMetadata={e=>setDuration(e.currentTarget.duration||0)}/>}
    <div><label className="text-sm font-bold">Visual style</label><select value={style} onChange={e=>setStyle(e.target.value)} className="mt-2 w-full rounded-xl border bg-background p-3">{STYLES.map(s=><option key={s}>{s}</option>)}</select></div>
    <div><label className="text-sm font-bold">Creative direction <span className="font-normal text-muted-foreground">(optional)</span></label><textarea value={concept} onChange={e=>setConcept(e.target.value)} rows={5} placeholder="Example: A lonely artist drives through a neon city at night, moving from heartbreak into confidence by sunrise." className="mt-2 w-full rounded-xl border bg-background p-3 resize-none"/></div>
    <Button className="w-full h-12 font-bold" disabled={!file||busy} onClick={storyboard}>{busy?<Loader2 className="mr-2 animate-spin"/>:<WandSparkles className="mr-2"/>}Create storyboard</Button>
    {status&&<div role="status" className="rounded-xl border bg-muted/30 p-3 text-sm">{status}</div>}
   </section>
   <section className="rounded-3xl border bg-card overflow-hidden">
    <div className="aspect-video bg-black relative"><canvas ref={canvas} width="1920" height="1080" className="w-full h-full object-cover"/>{!plan&&<div className="absolute inset-0 grid place-items-center text-center p-8"><div><Sparkles className="mx-auto w-10 h-10 text-primary mb-3"/><div className="text-xl font-black text-white">Director Preview</div><div className="text-sm text-white/60 mt-1">Your storyboard preview appears here.</div></div></div>}</div>
    <div className="p-5 flex flex-wrap gap-3 items-center"><Button variant="outline" disabled={!plan||!audio.current} onClick={()=>audio.current?.paused?audio.current?.play():audio.current?.pause()}><Play className="mr-2 w-4 h-4"/>Preview</Button><Button disabled={!plan||busy||allMotionBusy||ready<total} onClick={render}><Film className="mr-2 w-4 h-4"/>Render full video</Button>{video&&<a href={video} download={(file?.name?.replace(/\.[^.]+$/,"")||"nalibase-music-video")+".webm"}><Button variant="secondary"><Download className="mr-2 w-4 h-4"/>Download video</Button></a>}<span className="ml-auto text-xs text-muted-foreground">{total?`${ready}/${total} motion scenes ready`:"Waiting for storyboard"}</span></div>
   </section>
  </div>
  {plan?.scenes?.length>0&&<section className="space-y-4"><div className="flex flex-wrap gap-3 justify-between items-end"><div><div className="text-xs font-bold tracking-[.2em] text-primary">STORYBOARD</div><h2 className="text-2xl font-black">{plan.title||file?.name}</h2><p className="text-sm text-muted-foreground">{total} directed scenes · {ready} motion clips ready</p></div><Button onClick={generateAllMotion} disabled={allMotionBusy||busy||ready===total}>{allMotionBusy?<Loader2 className="mr-2 animate-spin"/>:<Sparkles className="mr-2"/>}{ready===total?"All motion ready":"Generate all motion"}</Button></div>
   <div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-4">{plan.scenes.map((s,i)=><article key={s.id||i} className="rounded-2xl border bg-card overflow-hidden"><div className="aspect-video bg-black">{s.video_url?<video src={s.video_url} controls muted loop playsInline className="w-full h-full object-cover"/>:s.image_url?<img src={s.image_url} alt="" className="w-full h-full object-cover"/>:<div className="w-full h-full grid place-items-center text-muted-foreground"><Film/></div>}</div><div className="p-4 space-y-3"><div className="flex gap-2 justify-between"><div><div className="text-xs text-primary font-bold">SCENE {i+1}</div><h3 className="font-black">{s.title||`Scene ${i+1}`}</h3></div>{s.video_url&&<span className="text-xs font-bold text-emerald-500">MOTION READY</span>}</div><p className="text-sm text-muted-foreground line-clamp-3">{s.prompt}</p>{s.motion&&<p className="text-xs"><span className="font-bold">Motion:</span> {s.motion}</p>}<Button size="sm" variant={s.video_url?"outline":"default"} className="w-full" disabled={clipBusy===s.id||allMotionBusy} onClick={()=>generateMotionClip(s)}>{clipBusy===s.id?<Loader2 className="mr-2 w-4 h-4 animate-spin"/>:<Sparkles className="mr-2 w-4 h-4"/>}{s.video_url?"Regenerate motion":"Generate motion"}</Button></div></article>)}</div>
  </section>}
 </div></div>;
}
