import { useEffect, useRef, useState } from "react";
import { ArrowLeft, Download, Film, Music2, Sparkles, Upload, Wand2 } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
const STYLES=[["Neon Pulse","#7c3aed","#ec4899"],["Midnight Fire","#ef4444","#f59e0b"],["Ocean Dream","#06b6d4","#2563eb"],["Emerald Motion","#10b981","#14b8a6"]];
export default function MusicVideoGenerator(){
 const navigate=useNavigate(),canvasRef=useRef(null),audioRef=useRef(null),rafRef=useRef(0),analyserRef=useRef(null),audioCtxRef=useRef(null);
 const [audioUrl,setAudioUrl]=useState(""),[name,setName]=useState(""),[style,setStyle]=useState(0),[rendering,setRendering]=useState(false),[progress,setProgress]=useState(0),[videoUrl,setVideoUrl]=useState("");
 useEffect(()=>()=>{cancelAnimationFrame(rafRef.current);},[]);
 const setupAudio=async()=>{const audio=audioRef.current;if(!audio)return;if(!audioCtxRef.current){const Ctx=window.AudioContext||window.webkitAudioContext,ctx=new Ctx(),an=ctx.createAnalyser();an.fftSize=256;an.smoothingTimeConstant=.82;analyserRef.current=an;audioCtxRef.current=ctx;const src=ctx.createMediaElementSource(audio);src.connect(an);an.connect(ctx.destination);}if(audioCtxRef.current.state==="suspended")await audioCtxRef.current.resume();};
 const draw=()=>{const c=canvasRef.current,a=audioRef.current;if(!c||!a)return;const x=c.getContext("2d"),w=c.width,h=c.height,t=a.currentTime||0,[label,c1,c2]=STYLES[style],g=x.createLinearGradient(0,0,w,h);g.addColorStop(0,c1);g.addColorStop(1,c2);x.fillStyle=g;x.fillRect(0,0,w,h);const data=new Uint8Array(analyserRef.current?.frequencyBinCount||128);analyserRef.current?.getByteFrequencyData(data);const avg=data.reduce((s,v)=>s+v,0)/(data.length||1);x.globalAlpha=.18;for(let i=0;i<24;i++){const r=40+((i*73+t*120)%420)+avg*.5;x.beginPath();x.arc(w/2+Math.sin(t*.7+i)*w*.28,h/2+Math.cos(t*.55+i)*h*.22,r,0,Math.PI*2);x.strokeStyle=i%2?c1:c2;x.lineWidth=18;x.stroke();}x.globalAlpha=1;const bars=64,bw=w/bars;for(let i=0;i<bars;i++){const v=(data[i]||0)/255,bh=80+v*h*.38;x.fillStyle="rgba(255,255,255,.72)";x.fillRect(i*bw,h-bh,bw*.62,bh);}x.textAlign="center";x.fillStyle="white";x.shadowColor="rgba(0,0,0,.45)";x.shadowBlur=30;x.font="900 86px system-ui";x.fillText(name.replace(/\\.[^.]+$/,"")||"NaliChat Music Video",w/2,h*.27);x.font="600 34px system-ui";x.fillText(label+" • HD animated visual",w/2,h*.34);x.shadowBlur=0;rafRef.current=requestAnimationFrame(draw);};
 useEffect(()=>{cancelAnimationFrame(rafRef.current);draw();return()=>cancelAnimationFrame(rafRef.current);},[style,name,audioUrl]);
 const onFile=e=>{const f=e.target.files?.[0];if(!f)return;if(audioUrl)URL.revokeObjectURL(audioUrl);setName(f.name);setAudioUrl(URL.createObjectURL(f));setVideoUrl("");};
 const generate=async()=>{const audio=audioRef.current,c=canvasRef.current;if(!audioUrl||!audio||!c)return;await setupAudio();audio.pause();audio.currentTime=0;setRendering(true);setProgress(0);setVideoUrl("");const cs=c.captureStream(30);let as;try{as=audio.captureStream?.()||audio.mozCaptureStream?.();}catch{}const tracks=[...cs.getVideoTracks(),...(as?.getAudioTracks()||[])],stream=new MediaStream(tracks),mime=["video/webm;codecs=vp9,opus","video/webm;codecs=vp8,opus","video/webm"].find(m=>MediaRecorder.isTypeSupported(m))||"",rec=new MediaRecorder(stream,mime?{mimeType:mime,videoBitsPerSecond:12000000}:undefined),chunks=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=()=>{const blob=new Blob(chunks,{type:rec.mimeType||"video/webm"});setVideoUrl(URL.createObjectURL(blob));setRendering(false);setProgress(100);tracks.forEach(t=>t.stop());};audio.ontimeupdate=()=>{if(audio.duration)setProgress(Math.min(99,Math.round(audio.currentTime/audio.duration*100)))};audio.onended=()=>{if(rec.state!=="inactive")rec.stop()};rec.start(1000);await audio.play();};
 return <div className="min-h-screen bg-background text-foreground pb-24"><div className="mx-auto max-w-6xl p-4 sm:p-6"><div className="flex items-center gap-3 mb-6"><Button variant="ghost" size="icon" onClick={()=>navigate(-1)}><ArrowLeft/></Button><div><h1 className="text-3xl font-black flex items-center gap-2"><Film className="text-primary"/>Music Video Generator</h1><p className="text-muted-foreground">Unlimited local renders • 1920×1080 HD • audio-reactive animation</p></div></div><div className="grid lg:grid-cols-[360px_1fr] gap-5"><section className="rounded-3xl border bg-card p-5 space-y-5"><label className="block rounded-2xl border-2 border-dashed border-primary/40 p-6 text-center cursor-pointer hover:bg-primary/5"><Upload className="mx-auto mb-2"/><b>Upload your song</b><p className="text-xs text-muted-foreground mt-1">MP3, WAV, M4A and browser-supported audio</p><input type="file" accept="audio/*" className="hidden" onChange={onFile}/></label>{name&&<div className="flex items-center gap-2 text-sm"><Music2 className="w-4 h-4 text-primary"/><span className="truncate">{name}</span></div>}<div><p className="font-bold mb-2">Animation style</p><div className="grid grid-cols-2 gap-2">{STYLES.map((s,i)=><button key={s[0]} onClick={()=>setStyle(i)} className={"rounded-xl border p-3 text-left text-xs font-bold "+(style===i?"border-primary bg-primary/10":"border-border")}>{s[0]}</button>)}</div></div><Button className="w-full h-12 font-bold" disabled={!audioUrl||rendering} onClick={generate}><Wand2 className="mr-2 w-4 h-4"/>{rendering?"Rendering "+progress+"%":"Generate HD Video"}</Button>{rendering&&<div className="h-2 rounded-full bg-secondary overflow-hidden"><div className="h-full bg-primary transition-all" style={{width:progress+"%"}}/></div>}{videoUrl&&<a href={videoUrl} download={(name.replace(/\\.[^.]+$/,"")||"nalichat")+"-animated-hd.webm"} className="flex items-center justify-center h-12 rounded-xl bg-emerald-600 text-white font-bold"><Download className="mr-2 w-4 h-4"/>Download HD Video</a>}<p className="text-xs text-muted-foreground">Rendering happens on your device, so NaliChat does not impose a generation-count limit. Speed depends on device performance and song length.</p></section><section className="rounded-3xl border bg-black overflow-hidden shadow-2xl"><div className="aspect-video relative"><canvas ref={canvasRef} width="1920" height="1080" className="w-full h-full"/>{!audioUrl&&<div className="absolute inset-0 flex flex-col items-center justify-center text-white/70"><Sparkles className="w-12 h-12 mb-3"/><b className="text-xl">Your animated video appears here</b></div>}</div><audio ref={audioRef} src={audioUrl} controls className="w-full" onPlay={setupAudio}/></section></div></div></div>;
}