#!/bin/bash

# NaliChat - Android AAB Build Script
# Run this script to generate a signed Android App Bundle for Google Play Store

set -e

echo "========================================="
echo "  NaliChat Android Build Script"
echo "========================================="

# ---- Step 1: Check dependencies ----
echo ""
echo "▶ Checking dependencies..."

if ! command -v node &> /dev/null; then
  echo "❌ Node.js not found. Install from https://nodejs.org"
  exit 1
fi

if ! command -v java &> /dev/null; then
  echo "❌ Java not found. Install JDK 17 from https://adoptium.net"
  exit 1
fi

echo "✅ Node.js: $(node -v)"
echo "✅ Java: $(java -version 2>&1 | head -1)"

# ---- Step 2: Install Bubblewrap ----
echo ""
echo "▶ Installing Bubblewrap CLI..."
npm install -g @bubblewrap/cli

# ---- Step 3: Generate keystore if it doesn't exist ----
if [ ! -f "./android.keystore" ]; then
  echo ""
  echo "▶ No keystore found. Generating a new one..."
  echo "⚠️  IMPORTANT: Save the keystore file and passwords somewhere safe!"
  echo "   You will need the SAME keystore for every future app update."
  echo ""
  keytool -genkey -v \
    -keystore ./android.keystore \
    -alias nalichat \
    -keyalg RSA \
    -keysize 2048 \
    -validity 10000 \
    -dname "CN=NaliChat, OU=Mobile, O=NaliChat, L=Indianapolis, S=Indiana, C=US"
  echo "✅ Keystore created at ./android.keystore"
else
  echo "✅ Using existing keystore: ./android.keystore"
fi

# ---- Step 4: Initialize or update TWA project ----
echo ""
if [ ! -f "./twa-manifest.json" ]; then
  echo "▶ No twa-manifest.json found. Initializing new TWA project..."
  bubblewrap init --manifest https://nalichat.org/manifest.json
  echo ""
  echo "⚠️  IMPORTANT: Verify packageId in twa-manifest.json is 'com.nalichat' before building!"
  echo "   The init command may generate a different package ID based on the domain."
  echo "   Edit twa-manifest.json and set: \"packageId\": \"com.nalichat\""
  exit 1
fi

echo "▶ twa-manifest.json found — using existing config"

# Only run bubblewrap update if the gradle project doesn't exist yet
if [ ! -f "./app/build.gradle" ] && [ ! -f "./app/build.gradle.kts" ]; then
  echo "  Gradle project not found — running 'bubblewrap update' to generate it..."
  bubblewrap update --skip-gradle-build || echo "⚠️  Update had issues — proceeding anyway"
else
  echo "  Gradle project found — skipping 'bubblewrap update' to preserve package ID"
fi

# ---- Step 5: Enforce package name com.nalichat everywhere ----
echo ""
echo "▶ Enforcing package name com.nalichat..."

# Cross-platform sed in-place edit (macOS needs -i '', Linux needs -i)
sed_inplace() {
  if [[ "$(uname)" == "Darwin" ]]; then
    sed -i '' "$@"
  else
    sed -i "$@"
  fi
}

# Fix twa-manifest.json packageId
MANIFEST_ID=$(grep -o '"packageId"[[:space:]]*:[[:space:]]*"[^"]*"' ./twa-manifest.json | head -1 | sed 's/.*: *//;s/"//g')
if [ "$MANIFEST_ID" != "com.nalichat" ]; then
  echo "  ⚠️  twa-manifest.json packageId is '$MANIFEST_ID' — fixing to 'com.nalichat'"
  sed_inplace "s/\"packageId\"[[:space:]]*:[[:space:]]*\"[^\"]*\"/\"packageId\": \"com.nalichat\"/g" ./twa-manifest.json
  echo "  ✅ twa-manifest.json packageId set to com.nalichat"
else
  echo "  ✅ twa-manifest.json packageId already correct: com.nalichat"
fi

# Fix build.gradle applicationId and namespace
GRADLE_FILE="./app/build.gradle"
if [ -f "$GRADLE_FILE" ]; then
  CURRENT_ID=$(grep -E "^\s*applicationId" "$GRADLE_FILE" | head -1 | sed "s/.*['\"]//;s/['\"].*//")
  echo "  Current applicationId in build.gradle: $CURRENT_ID"
  if [ "$CURRENT_ID" != "com.nalichat" ]; then
    echo "  ⚠️  applicationId is '$CURRENT_ID' — fixing to 'com.nalichat'"
    sed_inplace "s/applicationId [\"'].*[\"']/applicationId \"com.nalichat\"/g" "$GRADLE_FILE"
    sed_inplace "s/namespace [\"'].*[\"']/namespace \"com.nalichat\"/g" "$GRADLE_FILE"
    echo "  ✅ applicationId and namespace set to com.nalichat"
  else
    echo "  ✅ applicationId already correct"
  fi
else
  echo "  ⚠️  build.gradle not found at $GRADLE_FILE — will be generated by bubblewrap build"
fi

# Also check build.gradle.kts (Kotlin DSL variant)
GRADLE_KTS_FILE="./app/build.gradle.kts"
if [ -f "$GRADLE_KTS_FILE" ]; then
  echo "  Found build.gradle.kts — fixing there too..."
  sed_inplace "s/applicationId [\"'].*[\"']/applicationId \"com.nalichat\"/g" "$GRADLE_KTS_FILE"
  sed_inplace "s/namespace [\"'].*[\"']/namespace \"com.nalichat\"/g" "$GRADLE_KTS_FILE"
  echo "  ✅ build.gradle.kts fixed"
fi

# ---- Step 6: Build the AAB ----
echo ""
echo "▶ Building Android App Bundle (.aab)..."
bubblewrap build

# ---- Step 7: Verify the package name in the built AAB ----
echo ""
echo "▶ Verifying package name in built AAB..."
AAB_FILE="./app-release-bundle.aab"
if [ ! -f "$AAB_FILE" ]; then
  echo "❌ AAB file not found at $AAB_FILE — build may have failed"
  exit 1
fi

# Unzip the AAB and check the manifest for the package name
TMP_DIR=$(mktemp -d)
unzip -o "$AAB_FILE" "base/manifest/AndroidManifest.xml" -d "$TMP_DIR" 2>/dev/null || true
MANIFEST_XML="$TMP_DIR/base/manifest/AndroidManifest.xml"
if [ -f "$MANIFEST_XML" ]; then
  # AndroidManifest.xml in AAB is compiled binary XML — extract package with strings
  AAB_PACKAGE=$(strings "$MANIFEST_XML" | grep -i "com.nalichat" | head -1)
  if echo "$AAB_PACKAGE" | grep -q "com.nalichat"; then
    echo "  ✅ Package name in AAB: com.nalichat"
  else
    echo "  ⚠️  Could not verify com.nalichat in binary manifest."
    echo "  Checking with aapt2 if available..."
    if command -v aapt2 &> /dev/null; then
      aapt2 dump packagename "$AAB_FILE" 2>/dev/null || echo "  (aapt2 dump failed — proceeding)"
    fi
  fi
else
  echo "  ⚠️  Could not extract AndroidManifest.xml from AAB for verification"
fi
rm -rf "$TMP_DIR"

# ---- Step 8: Done ----
echo ""
echo "========================================="
echo "  ✅ Build Complete!"
echo "========================================="
echo ""
echo "Your signed AAB is ready at:"
echo "  ./app-release-bundle.aab"
echo ""
echo "Upload it to Google Play Console:"
echo "  https://play.google.com/console"
echo ""
echo "For the Digital Asset Links verification, add this to:"
echo "  public/.well-known/assetlinks.json"
echo "(Run: bubblewrap fingerprint to get your SHA-256)"